## Murari Khatiwada
##06.25.2021
##R Program Assignhment 2
##this program will create a matrix that can have inverse solution and find the 
##inverse of the matrix
library(MASS)
makeCacheMatrix <- function(x = matrix()) {
  m<- NULL
  set <- function(y){
    x <<- y ## Function inside another function (double arrow)
    m <<- NULL
  }
  get <- function()x ## get value of matrix
  setInverse <- function(inverse) m <<- inverse ## set value of inverse
  getInverse <- function()m  ## get value of inverse
  list(set = set, get = get, setInverse = setInverse,getInverse = getInverse)
}

## computing the inverse of the matrix generated by above makeCacheMatrix function
cacheSolve <- function(x, ...){
    ## Return a matrix that is the inverse of 'x'
      m <- x$getInverse()
    if(!is.null(m)){
      message("getting cached data")
      return(m)
    }
          mat <- x$get()
    m <- solve(mat,...)
    x$setInverse(m) ##set Inverse
    m     
  }
